server:
  port: 8090
  contextPath: /heroes
  error:
    whitelabel:
      enabled: true
spring:
    jpa:
        database: MYSQL
         # hibernate:
        #   ddl-auto: create

    datasource:
        url: jdbc:mysql://localhost:3306/heroes
        username: root
        password: uhbujhbq
        name: boot
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
      throw-exception-if-no-handler-found: true


